#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker2"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "34ffed3a24a14d378ce41e0ae8d8681b" }
]

[assets]
directory = "./public"
